# Generated by Django 2.0.1 on 2019-10-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_custom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='profile_pic',
            field=models.FileField(default=None, upload_to='userimages'),
            preserve_default=False,
        ),
    ]
