# Generated by Django 2.0.1 on 2019-10-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
