# Generated by Django 2.0.1 on 2019-10-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20191017_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='cost',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='items',
            field=models.IntegerField(default='0'),
        ),
    ]
