# Generated by Django 2.0.1 on 2019-10-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serialprac', '0003_auto_20191013_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_library',
            name='person',
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
