# Generated by Django 2.0.1 on 2019-10-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarServiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=25)),
                ('car_model', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=4)),
                ('service_type', models.CharField(max_length=25)),
                ('service_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('dob', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('postal', models.IntegerField(max_length=8)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='carservicedetail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.SchedulerDetails'),
        ),
    ]
