# Generated by Django 2.0.1 on 2019-10-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerdetails',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedulerdetails',
            name='postal',
            field=models.IntegerField(),
        ),
    ]
