# Generated by Django 2.0.1 on 2019-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_auto_20191012_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservicedetail',
            name='service_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedulerdetails',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schedulerdetails',
            name='city',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='schedulerdetails',
            name='country',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='schedulerdetails',
            name='dob',
            field=models.DateField(auto_now_add=True),
        ),
    ]
