# Generated by Django 2.0.1 on 2019-10-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_auto_20191013_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservicedetail',
            name='service_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedulerdetails',
            name='dob',
            field=models.DateField(),
        ),
    ]
